/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.ArrayList;
import model.Story;
import model.GameCharacter;
import model.StoryChoice;
import controller.StoryControl;
import controller.CharacterControl;
import controller.GameController;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lenovo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private JPanel mainPanel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    private StoryControl storyControl;
    private CharacterControl characterControl;
    private GameController gameControl;
    
    
    public MainFrame() { // Initialize story, character, and game controllers
        initComponents();
        storyControl = new StoryControl(jTable1); 
        characterControl = new CharacterControl();
        gameControl = new GameController();
        loadCharactersToTable(); // Load all characters into the table display
        loadStoriesToComboBox(); // Populate story dropdown with available stories
        
        // Set column headers for character table
        DefaultTableModel charModel = (DefaultTableModel) jTable2.getModel();
        charModel.setColumnIdentifiers(new Object[]{"Name", "Class", "Level"});
        
        // Set column headers for story table
        DefaultTableModel storyModel = (DefaultTableModel) jTable1.getModel();
        storyModel.setColumnIdentifiers(new Object[]{"Title","Premise","Difficulty"});
    }
    public JPanel getMainPanel() {
        return MainPanel;
    }
    
    private void loadStoriesToComboBox() {
        storyComboBox.removeAllItems();

        for (int i = 0; i < storyControl.getStoryCount(); i++) {
            Story s = storyControl.getStory(i);
            storyComboBox.addItem(s.getTitle());
        }
    }
    private void addScoreFromPoints(int points) { // Add points to player's score and update progress bar
        gameControl.addScore(points);
        scoreProgressBar.setValue(gameControl.getScore());
    }
    
    private void loadCharactersToTable() { // Refresh character table with current data
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        // Add each character as a new row
        for (GameCharacter c : characterControl.getCharacters()) {
            model.addRow(new Object[]{
                c.getName(),
                c.getClazz(),
                c.getLevel()
            });
        }
    }
    // Load next three story choices from queue
    private void loadNextChoices() {

        StoryChoice c1 = gameControl.nextChoice();
        StoryChoice c2 = gameControl.nextChoice();
        StoryChoice c3 = gameControl.nextChoice();

        
        setupChoiceButton(choice1Button, c1);
        setupChoiceButton(choice2Button, c2);
        setupChoiceButton(choice3Button, c3);

        // End game if no choices remain
        if (c1 == null && c2 == null && c3 == null) {
            gameControl.finishGame();
        }
    }
    // Configure button with choice text and data
    private void setupChoiceButton(JButton button, StoryChoice choice) {
        if (choice == null) {
            button.setVisible(false);        
            button.putClientProperty("choice", null);
        } else {
            button.setVisible(true);         
            button.setText(choice.getText()); 
            button.putClientProperty("choice", choice); 
        }
    }
    // Process player's choice selection
    private void handleChoice(JButton button) {
        StoryChoice choice = (StoryChoice) button.getClientProperty("choice");

        if (choice == null) return;

        // Apply choice effects to character
        gameControl.applyChoice(choice);
        scoreProgressBar.setValue(gameControl.getScore());

        // Display choice feedback in story area
        storyTextArea.append("\n\nYou chose: " + choice.getText() +
                             " (+" + choice.getPoints() + " points)");

        
        loadNextChoices(); // Load next set of choices
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Signup = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        AdminDashboard = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton22 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        UserHomePage = new javax.swing.JPanel();
        CharacterList = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        CharacterCreation = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        characterNameField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox<>();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        StorySelection = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        storyComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        storyIntroTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        searchStoryField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        RolePlay = new javax.swing.JPanel();
        scoreProgressBar = new javax.swing.JProgressBar();
        choice1Button = new javax.swing.JButton();
        choice3Button = new javax.swing.JButton();
        choice2Button = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        storyTextArea = new javax.swing.JTextArea();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        Signup.setBackground(new java.awt.Color(0, 0, 0));
        Signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 76, 76));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Signup.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 70, 20));

        jButton2.setBackground(new java.awt.Color(0, 76, 76));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Signup.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin login?");
        Signup.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, 10));

        jLabel15.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email");
        Signup.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel2.setText("SIGN UP AS USER");
        Signup.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        emailTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Signup.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 80, -1));

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        Signup.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        Signup.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm ");
        Signup.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 60, 40));

        nameTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Signup.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 80, -1));

        jPasswordField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Signup.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 80, -1));

        jPasswordField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        Signup.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 80, -1));

        jLabel21.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("password");
        Signup.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/Background.png"))); // NOI18N
        Signup.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        jLabel28.setText("jLabel28");
        Signup.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        MainPanel.add(Signup, "card4");

        Login.setBackground(new java.awt.Color(0, 0, 0));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, -1));

        passwordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        Login.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 80, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel6.setText("LOGIN AS ADMIN");
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        Login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        Login.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 76, 76));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Login.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 76, 76));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Go back to sign-up");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Login.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/Background.png"))); // NOI18N
        Login.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainPanel.add(Login, "card5");

        AdminDashboard.setBackground(new java.awt.Color(250, 232, 190));
        AdminDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Story Title");
        AdminDashboard.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel12.setText("Premise");
        AdminDashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel13.setText("Difficulty");
        AdminDashboard.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jTextField3.setBackground(new java.awt.Color(0, 76, 76));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AdminDashboard.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 250, -1));

        jTextArea1.setBackground(new java.awt.Color(0, 76, 76));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextArea1);

        AdminDashboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 250, 66));

        jButton5.setBackground(new java.awt.Color(0, 76, 76));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ADD");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        AdminDashboard.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 70, -1));

        jButton8.setBackground(new java.awt.Color(0, 76, 76));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Delete");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        AdminDashboard.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 70, -1));

        jTable1.setBackground(new java.awt.Color(0, 76, 76));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Premise", "Difficulty"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        AdminDashboard.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 320, 240));

        jPanel2.setBackground(new java.awt.Color(54, 34, 11));

        jLabel9.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Admin Dashboard");

        jButton11.setBackground(new java.awt.Color(0, 76, 76));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Logout");
        jButton11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(0, 76, 76));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));

        jButton21.setBackground(new java.awt.Color(0, 76, 76));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Search");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton21)
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jButton11))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21))))
                .addContainerGap())
        );

        AdminDashboard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        jButton10.setBackground(new java.awt.Color(0, 76, 76));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Update");
        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        AdminDashboard.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 70, -1));

        jComboBox2.setBackground(new java.awt.Color(0, 76, 76));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        AdminDashboard.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jButton22.setBackground(new java.awt.Color(0, 76, 76));
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Sort");
        jButton22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        AdminDashboard.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 70, -1));
        AdminDashboard.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));
        AdminDashboard.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/clock.png"))); // NOI18N
        AdminDashboard.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 120, 160));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/decorativebgstamp.png"))); // NOI18N
        AdminDashboard.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        MainPanel.add(AdminDashboard, "card3");

        UserHomePage.setLayout(new java.awt.CardLayout());

        CharacterList.setBackground(new java.awt.Color(242, 227, 184));
        CharacterList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 76, 76));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Create");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        CharacterList.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 76, 76));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Select");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        CharacterList.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 76, 76));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        CharacterList.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        jPanel1.setBackground(new java.awt.Color(54, 34, 11));

        jLabel16.setFont(new java.awt.Font("Wide Latin", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Character List");

        jButton17.setBackground(new java.awt.Color(0, 76, 76));
        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Logout");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(44, 44, 44)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        CharacterList.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jButton16.setBackground(new java.awt.Color(0, 76, 76));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Sort");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        CharacterList.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/character list bg.png"))); // NOI18N
        CharacterList.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 560));

        jTable2.setBackground(new java.awt.Color(0, 76, 76));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Class", "Level"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        CharacterList.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, 340));

        UserHomePage.add(CharacterList, "card5");

        CharacterCreation.setBackground(new java.awt.Color(239, 220, 176));
        CharacterCreation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel22.setText("Character Name");
        CharacterCreation.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 165, -1, 30));
        CharacterCreation.add(characterNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 112, -1));

        jLabel24.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel24.setText("Class");
        CharacterCreation.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        classComboBox.setBackground(new java.awt.Color(0, 76, 76));
        classComboBox.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        classComboBox.setForeground(new java.awt.Color(255, 255, 255));
        classComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warrier", "Mage", "Rogue", "Archer" }));
        classComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classComboBoxActionPerformed(evt);
            }
        });
        CharacterCreation.add(classComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jButton18.setBackground(new java.awt.Color(0, 76, 76));
        jButton18.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Save Character");
        jButton18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        CharacterCreation.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 100, -1));

        jButton19.setBackground(new java.awt.Color(0, 76, 76));
        jButton19.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Cancel");
        jButton19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        CharacterCreation.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 100, -1));

        jPanel3.setBackground(new java.awt.Color(54, 34, 11));

        jLabel14.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Character Creation");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel34))
        );

        CharacterCreation.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jLabel27.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel27.setText("level");
        CharacterCreation.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(0, 76, 76));
        jToggleButton1.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Generate Level");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        CharacterCreation.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        CharacterCreation.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 90, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/character creation bg.png"))); // NOI18N
        CharacterCreation.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 550));

        UserHomePage.add(CharacterCreation, "charactercreation");

        StorySelection.setBackground(new java.awt.Color(239, 220, 176));
        StorySelection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel17.setText("Select Story");
        StorySelection.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jButton12.setBackground(new java.awt.Color(0, 76, 76));
        jButton12.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Play Story");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        StorySelection.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 499, -1, -1));

        jButton13.setBackground(new java.awt.Color(0, 76, 76));
        jButton13.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Back");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        StorySelection.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 534, -1, -1));

        jLabel19.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel19.setText("Story Intro");
        StorySelection.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        storyComboBox.setBackground(new java.awt.Color(0, 76, 76));
        storyComboBox.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        storyComboBox.setForeground(new java.awt.Color(255, 255, 255));
        storyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        storyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storyComboBoxActionPerformed(evt);
            }
        });
        StorySelection.add(storyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        storyIntroTextArea.setEditable(false);
        storyIntroTextArea.setBackground(new java.awt.Color(0, 76, 76));
        storyIntroTextArea.setColumns(20);
        storyIntroTextArea.setForeground(new java.awt.Color(255, 255, 255));
        storyIntroTextArea.setLineWrap(true);
        storyIntroTextArea.setRows(5);
        storyIntroTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(storyIntroTextArea);

        StorySelection.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 270, 228));

        jPanel4.setBackground(new java.awt.Color(54, 34, 11));

        jLabel18.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Story Selection");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addGap(92, 92, 92)
                .addComponent(jLabel18)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel36))
        );

        StorySelection.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        jButton20.setBackground(new java.awt.Color(0, 76, 76));
        jButton20.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Search");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        StorySelection.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        searchStoryField.setBackground(new java.awt.Color(0, 76, 76));
        searchStoryField.setForeground(new java.awt.Color(255, 255, 255));
        searchStoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStoryFieldActionPerformed(evt);
            }
        });
        StorySelection.add(searchStoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 261, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/Story Selection.png"))); // NOI18N
        StorySelection.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        UserHomePage.add(StorySelection, "card3");

        RolePlay.setBackground(new java.awt.Color(239, 220, 176));
        RolePlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scoreProgressBar.setStringPainted(true);
        RolePlay.add(scoreProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 387, 13));

        choice1Button.setBackground(new java.awt.Color(0, 76, 76));
        choice1Button.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        choice1Button.setForeground(new java.awt.Color(255, 255, 255));
        choice1Button.setText("Choice 1");
        choice1Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        choice1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice1ButtonActionPerformed(evt);
            }
        });
        RolePlay.add(choice1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        choice3Button.setBackground(new java.awt.Color(0, 76, 76));
        choice3Button.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        choice3Button.setForeground(new java.awt.Color(255, 255, 255));
        choice3Button.setText("Choice 3");
        choice3Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        choice3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice3ButtonActionPerformed(evt);
            }
        });
        RolePlay.add(choice3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        choice2Button.setBackground(new java.awt.Color(0, 76, 76));
        choice2Button.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        choice2Button.setForeground(new java.awt.Color(255, 255, 255));
        choice2Button.setText("Choice 2");
        choice2Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        choice2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice2ButtonActionPerformed(evt);
            }
        });
        RolePlay.add(choice2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        storyTextArea.setEditable(false);
        storyTextArea.setBackground(new java.awt.Color(0, 76, 76));
        storyTextArea.setColumns(20);
        storyTextArea.setRows(5);
        storyTextArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane5.setViewportView(storyTextArea);

        RolePlay.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 393, 369));

        jButton14.setBackground(new java.awt.Color(0, 76, 76));
        jButton14.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Finish story");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        RolePlay.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        jButton15.setBackground(new java.awt.Color(0, 76, 76));
        jButton15.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Exit");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        RolePlay.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jPanel5.setBackground(new java.awt.Color(54, 34, 11));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 76, 76));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(123, 123, 123)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        RolePlay.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/roleplayicon.png"))); // NOI18N
        RolePlay.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/images/Roleplaybg.png"))); // NOI18N
        jLabel38.setText("jLabel38");
        RolePlay.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 590));

        UserHomePage.add(RolePlay, "card2");

        MainPanel.add(UserHomePage, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "charactercreation");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jTable2.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select a character");
            return;
        }
        
        
        if (storyComboBox.getSelectedIndex() != -1) {
            Story selectedStory = storyControl.getStory(storyComboBox.getSelectedIndex());
            storyIntroTextArea.setText(selectedStory.getIntro());
        }

        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "card3");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void classComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classComboBoxActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String name = characterNameField.getText();
        String clazz = classComboBox.getSelectedItem().toString();
        int level = 0;
        


        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter character name");
            return;
        }
        
        if (jTextField4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Generate a level first");
            return;
        }
        
        try {
            level = Integer.parseInt(jTextField4.getText());
            characterControl.addCharacter(name, clazz, level);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Level must be a number",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE);
        }

        characterControl.addCharacter(name, clazz, level);

        loadCharactersToTable(); 

        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "card5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int charIndex = jTable2.getSelectedRow();
        int storyIndex = storyComboBox.getSelectedIndex();

        if (charIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select a character");
            return;
        }
        
        if (storyIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select a story");
            return;
        }

        GameCharacter selectedCharacter = null;
        int i = 0;

        for (GameCharacter gc : characterControl.getCharacters()) {
            if (i == charIndex) {
                selectedCharacter = gc;
                break;
            }
            i++;
        }

        if (selectedCharacter == null) {
            JOptionPane.showMessageDialog(this, "Invalid character selection");
            return;
        }

        Story selectedStory = storyControl.getStory(storyIndex);
        
        if (selectedStory == null) {
            JOptionPane.showMessageDialog(this, "Invalid story selection");
            return;
        }
        
        gameControl.startGame(selectedCharacter, selectedStory);
        
        storyTextArea.setText(selectedStory.getIntro());
        
        jTextField1.setText(selectedStory.getTitle());
        
        
        
        ArrayList<StoryChoice> choices = selectedStory.getChoices();
        if (choices.size() > 0){ 
            choice1Button.setText(choices.get(0).getText());
            choice1Button.putClientProperty("choice", choices.get(0));
            choice1Button.setVisible(true);
        }else {
            choice1Button.setVisible(false);
        }
        if (choices.size() > 1){ 
            choice2Button.setText(choices.get(1).getText());
            choice2Button.putClientProperty("choice", choices.get(1));  
            choice2Button.setVisible(true);
        }else {
            choice2Button.setVisible(false);
        }
        if (choices.size() > 2){ 
            choice3Button.setText(choices.get(2).getText());
            choice3Button.putClientProperty("choice", choices.get(2));  
            choice3Button.setVisible(true);
        }else {
            choice3Button.setVisible(false);
        }
        
        scoreProgressBar.setValue(selectedCharacter.getScore());

        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "card2");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void choice2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice2ButtonActionPerformed
        handleChoice(choice2Button);      // TODO add your handling code here:
    }//GEN-LAST:event_choice2ButtonActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "CharacterList");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "CharacterList");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        gameControl.finishGame();
        
        
        loadCharactersToTable();
        
        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "card5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        CardLayout cl = (CardLayout) UserHomePage.getLayout();
        cl.show(UserHomePage, "CharacterList");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a character to delete");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this character?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            characterControl.deleteCharacter(selectedRow);
            loadCharactersToTable();
            JOptionPane.showMessageDialog(this, "Character deleted successfully!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void choice1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice1ButtonActionPerformed
        handleChoice(choice1Button);
            // TODO add your handling code here:
    }//GEN-LAST:event_choice1ButtonActionPerformed

    private void choice3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice3ButtonActionPerformed
        handleChoice(choice3Button);        // TODO add your handling code here:
    }//GEN-LAST:event_choice3ButtonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        storyControl.updateStory(
            jTextField3.getText(),
            jTextArea1.getText(),
            jComboBox2.getSelectedItem().toString()
        );   // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        storyControl.deleteStory();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        storyControl.addStory(
            jTextField3.getText(),
            jTextArea1.getText(),
            jComboBox2.getSelectedItem().toString()
        );        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = nameTextField.getText().trim();
        String email = emailTextField.getText().trim();
        String pass1 = new String(jPasswordField1.getPassword());
        String pass2 = new String(jPasswordField2.getPassword());

        if (name.isEmpty() || email.isEmpty() || pass1.isEmpty() || pass2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields");
            return;
        }

        if (!pass1.equals(pass2)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match");
            return;
        }

        JOptionPane.showMessageDialog(this, "Signup successful!");

        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card2");                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String username = usernameTextField.getText();
        String password = new String(passwordField.getPassword());

        if (username.equals("admin") && password.equals("admin123")) {
            JOptionPane.showMessageDialog(this, "Admin login successful");

            CardLayout cl = (CardLayout) MainPanel.getLayout();
            cl.show(MainPanel, "card3"); 
        } else {
            JOptionPane.showMessageDialog(this, "Invalid admin credentials");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card4");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        characterControl.sortByLevel();
        loadCharactersToTable();
        JOptionPane.showMessageDialog(this, "Characters sorted by level");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        String keyword = searchStoryField.getText().trim();

        if (keyword.isEmpty()) {
            loadStoriesToComboBox(); 
            return;
        }

        storyComboBox.removeAllItems();

        for (int i = 0; i < storyControl.getStoryCount(); i++) {
            Story s = storyControl.getStory(i);
            if (s.getTitle().toLowerCase().contains(keyword.toLowerCase())) {
                storyComboBox.addItem(s.getTitle());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void searchStoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchStoryFieldActionPerformed

    private void storyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storyComboBoxActionPerformed
        String selectedTitle = (String) storyComboBox.getSelectedItem();
        if (selectedTitle == null) return;

        Story s = storyControl.findStoryByTitle(selectedTitle);

        if (s != null) {
            storyIntroTextArea.setText(s.getIntro());
            storyIntroTextArea.setEditable(false); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_storyComboBoxActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        String keyword = jTextField2.getText().trim();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a story title");
            return;
        }

        storyControl.sortStoriesByTitle(); // REQUIRED for binary search

        Story result = storyControl.binarySearchByTitle(keyword);

        if (result != null) {
            JOptionPane.showMessageDialog(this,
                "Story Found:\n" +
                result.getTitle() + "\n" +
                result.getIntro() + "\n" +
                result.getDifficulty()
            );
        } else {
            JOptionPane.showMessageDialog(this, "Story not found");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        storyControl.sortStoriesByTitle();
        JOptionPane.showMessageDialog(this, "Stories sorted by title");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int min = 1;
        int max = 13;

        int generatedLevel = (int) (Math.random() * (max - min + 1)) + min;

        jTextField4.setText(String.valueOf(generatedLevel));        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminDashboard;
    private javax.swing.JPanel CharacterCreation;
    private javax.swing.JPanel CharacterList;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RolePlay;
    private javax.swing.JPanel Signup;
    private javax.swing.JPanel StorySelection;
    private javax.swing.JPanel UserHomePage;
    private javax.swing.JTextField characterNameField;
    private javax.swing.JButton choice1Button;
    private javax.swing.JButton choice2Button;
    private javax.swing.JButton choice3Button;
    private javax.swing.JComboBox<String> classComboBox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JProgressBar scoreProgressBar;
    private javax.swing.JTextField searchStoryField;
    private javax.swing.JComboBox<String> storyComboBox;
    private javax.swing.JTextArea storyIntroTextArea;
    private javax.swing.JTextArea storyTextArea;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}

